In [1]:
import pandas as pd

df = pd.read_csv('data/bids.csv')

In [2]:
print df.head(5);

   bid_id                              bidder_id auction merchandise  device  \
0       0  8dac2b259fd1c6d1120e519fb1ac14fbqvax8   ewmzr     jewelry  phone0   
1       1  668d393e858e8126275433046bbd35c6tywop   aeqok   furniture  phone1   
2       2  aa5f360084278b35d746fa6af3a7a1a5ra3xe   wa00e  home goods  phone2   
3       3  3939ac3ef7d472a59a9c5f893dd3e39fh9ofi   jefix     jewelry  phone4   
4       4  8393c48eaf4b8fa96886edc7cf27b372dsibi   jefix     jewelry  phone5   

               time country              ip              url  
0  9759243157894736      us   69.166.231.58  vasstdc27m7nks3  
1  9759243157894736      in   50.201.125.84  jmqlhflrzwuay9c  
2  9759243157894736      py  112.54.208.157  vasstdc27m7nks3  
3  9759243157894736      in   18.99.175.133  vasstdc27m7nks3  
4  9759243157894736      in    145.138.5.37  vasstdc27m7nks3  


In [3]:
print len(df['device'].unique())
print len(df['bidder_id'].unique())
print len(df['ip'].unique())

7351
6614
2303991


In [4]:
print len((df['url'].unique()))
print len(df['auction'].unique())

1786351
15051


In [9]:
m_f_bids = df.as_matrix()

array([[2, 'aa5f360084278b35d746fa6af3a7a1a5ra3xe', 'wa00e', ..., 'py',
        '112.54.208.157', 'vasstdc27m7nks3'],
       [27, 'aa5f360084278b35d746fa6af3a7a1a5ra3xe', '88xe3', ..., 'ch',
        '144.203.164.7', '526pa711hpwgwta'],
       [84, 'aa5f360084278b35d746fa6af3a7a1a5ra3xe', 'h1ko2', ..., 'tr',
        '170.92.227.44', 'vasstdc27m7nks3'],
       ..., 
       [2351100, 'aa5f360084278b35d746fa6af3a7a1a5ra3xe', 'r1wfm', ...,
        'vn', '34.206.123.215', 'vasstdc27m7nks3'],
       [2351114, 'aa5f360084278b35d746fa6af3a7a1a5ra3xe', 'kc1y2', ...,
        'my', '188.173.123.55', 'vasstdc27m7nks3'],
       [2351126, 'aa5f360084278b35d746fa6af3a7a1a5ra3xe', 'vqe7e', ...,
        'pa', '109.234.79.220', 'vasstdc27m7nks3']], dtype=object)

In [10]:
%timeit m_f_bids[m_f_bids[:, 1] == "aa5f360084278b35d746fa6af3a7a1a5ra3xe"]

10 loops, best of 3: 174 ms per loop


In [56]:
import numpy as np
filtered = m_f_bids[m_f_bids[:, 1] == "624f258b49e77713fc34034560f93fb3hu3jo"]
# %timeit np.unique(filtered[:, 4]).shape[0]

In [57]:
times = filtered[:, 5].astype(np.int64)
t1, t2 = times[:-1], times[1:]

In [61]:
print times
t_diff = times[1:] - times[:-1]
print t_diff

[9764047105263157 9766036421052631 9770514263157894]
[1989315789474 4477842105263]
1989315789474


In [55]:
df = pd.DataFrame(filtered[:, [1, 2]], index=filtered[:, 0], columns=['bid_id', 'auction'])
# df.head()
gp = df.groupby(['auction']).count()['bid_id']
print gp

auction
0cuy6       2
0zqjp       3
122l6       1
126v6       1
12a00      66
16nyi       1
1aqjf      19
1ez89       3
1f9t0      19
1ftck       7
1gmv9       1
1phic       3
1r07r       1
1z6y5       2
22mr6       2
...
y50y6       2
yb37a      14
yduus       1
yiapr       2
yje37       1
yo1by       4
ypj1s       2
ywmkf       2
yy6dx       1
zc8fu       1
zd01o       8
zfjly       3
zm2v1       1
zpwjd       1
zwbn5       5
Name: bid_id, Length: 269, dtype: int64


In [36]:
import numpy as np 
import pandas as pd
b_id = '11'
filtered = np.loadtxt("data/f_bidder_id/%s.csv" % b_id, delimiter=',', dtype='str')
df = pd.read_csv('data/bids.csv')
df = df.as_matrix()
df = df[df[:, 1]=='fa64831ab5ade55daee13f852c16b0a84ujt0']
print np.unique(df[:, 6]).shape[0]
print np.unique(filtered[:, 4]).shape[0]

53
53


/usr/lib/python2.7/site-packages/numpy/lib/arraysetops.py:198: FutureWarning: numpy not_equal will not check object identity in the future. The comparison did not return the same result as suggested by the identity (`is`)) and will change.
  flag = np.concatenate(([True], aux[1:] != aux[:-1]))


In [29]:
df = pd.DataFrame(filtered[:, :2], columns=['auction', 'something'])
bids_count = df.groupby(['auction']).count()['something']
print bids_count


auction
0cuy6    1
0d5z1    1
1f9t0    2
1pi3q    4
272z1    1
28dgm    3
29plp    1
2hu2f    1
2qrds    3
2rzxk    3
2vijf    1
33p2a    1
3zewh    2
436hc    1
47xug    2
4goa0    1
4s9ut    1
52b8i    1
557vg    2
5aviv    1
5tdxp    1
5umtc    1
62d9x    1
7ryke    1
7us95    1
7vwnx    1
860ny    1
8ufmo    1
8wi2r    3
8ymn3    1
        ..
rcsi0    3
rp76w    1
s8ys6    2
sktys    1
snp74    8
svwdv    2
tq1bk    2
tqpu1    2
uotsf    2
uu6z3    1
uvnl7    1
uzj32    1
v6jlp    2
v7931    3
v8r5s    3
vjfp5    1
vsmcx    1
vw7uy    1
wo635    1
x8eax    6
x8et8    1
xdel4    1
xofhf    1
xsj5g    4
y8x4o    2
yb37a    1
yis3j    1
yo1by    2
zd01o    1
zh1dw    2
Name: something, dtype: int64


In [23]:
np.where(filtered[:, 0] == 'qyr4w')

(array([20, 21]),)